### ISSUE TITLE
Pre-commit hook fails if removing .docx files

### ISSUE THREAD

**Issue by dtdoering** [vigente/gerardus#102]
Using the `pre-commit-git-diff-docx.sh` script, the commit fails if one of the staged changes includes deleting a `*.docx` file that has previously been tracked in the repo. Steps to reproduce below:

```
# Create foo.docx and bar.docx using Word

$ git add .
$ git commit -m "Add foo.docx, bar.docx"
$ rm foo.docx
$ git add .
$ git commit -m "Remove foo.docx"

# Fails to convert foo.docx to markdown: file does not exist
# Commit fails
```

I have created a fix in #101 by adding the `--diff-filter=d` option to exclude deleted files from `pandoc`, which necessitated an extra loop to remove the markdown copies of the removed `*.docx` files.

_Side note: I am using your pre- and post-commit hooks to advertise `git` as a VCS for research manuscripts in our lab, agnostic to whether people edit their documents in Word or not. It's working great so far!_

**Comment by rcasero** [comment]
Note to self: This was addressed in pull request #101
