### ISSUE TITLE
Wiki files

### ISSUE THREAD

**Issue by ytakemon** [vigente/gerardus#103]
To whom this may concern,
 
I really liked how easy it was to follow your instructions on your wiki regarding integrating docx files to github workflow. I tried forking your repo, but that did not copy over your wiki. Would you be okay with me cloning your wiki and pushing it into my Git_recourse repo? I will give your group credit in my README.md . 

Regards,
ytakemon

**Comment by rcasero** [comment]
Hi @ytakemon . Sorry for the very slow reply. I think it's more useful if you link to the wiki. That way, if we make changes to the .docx hooks (as we just did in #101 ), and the documentation needs to change, the info will be up to date. That said, if you still want to clone and attribute, that's fine.
