### ISSUE TITLE
Spaces in filenames and paths breaks the pre- and post-commit scripts

### ISSUE THREAD

**Issue by DouglasUrner** [vigente/gerardus#109]
The subject pretty much says it all.

I'll see if I can come up with a fix and make a pull request.

**Comment by rcasero** [comment]
Probably all that's needed is to enclose in double quotes ("") path variables, e.g. $SOME_DIR -> "$SOME_DIR"

**Comment by code-11** [comment]
Perhaps you can change IFS=$'\n' and then unset it later?

**Comment by yya518** [comment]
very useful tool! thanks for your contribution. Wish you could fix the filename space issue.

**Comment by rcasero** [comment]
Sorry, I'm not developing in Matlab anymore. But if you want to try one of the fixes above and send a pull request, I'll check it.

**Comment by scfast** [comment]
I've just created a PR for this (#112). I've run it against a few documents with multiple words in the file name (i.e. "my example document.docx")

**Comment by rcasero** [comment]
Thanks, @scfast . I have replied in your PR.
