### ISSUE TITLE
Trivial comment

### ISSUE THREAD

**Issue by giammi56** [vigente/gerardus#113]
in the instructions for windows is it said to look for "C:\Document and settings" folder.
From Windows Vista on it has been deprecated in favour of "C:\Users\YourUserID\AppData\Local" .

and I would modify the target user.giconfig according to this gui de https://www.theserverside.com/blog/Coffee-Talk-Java-News-Stories-and-Opinions/Where-system-global-and-local-Windows-Git-config-files-are-saved

source: https://answers.microsoft.com/en-us/windows/forum/windows_10-files-winpc/documents-and-settings-in-windows-10/be87dd2d-f903-427f-b501-932a3a2999d1

**Comment by rcasero** [comment]
Sorry, giammi56, I'm no longer maintaining this, and cannot check it. But thanks for the comment
